In [25]:
result=[]
import random as rand
import pandas as pd
file='test.csv'
#file='train_data.csv'
data=pd.read_csv(file)
data

     outlook temperature humidity windy play
0      sunny         hot     high     f   no
1      sunny         hot     high     t   no
2   overcast         hot     high     f  yes
3      rainy        mild     high     f  yes
4      rainy        cool   normal     f  yes
5      rainy        cool   normal     t   no
6   overcast        cool   normal     t  yes
7      sunny        mild     high     f   no
8      sunny        cool   normal     f  yes
9      rainy        mild   normal     f  yes
10     sunny        mild   normal     t  yes
11  overcast        mild     high     t  yes
12  overcast         hot   normal     f  yes
13     rainy        mild     high     t   no

In [26]:

for i in range(data.shape[1]-1):
    result.append(pd.crosstab(index=data.iloc[:,i],columns=data.iloc[:,4]))
print(result)  
print("\n")

[play      no  yes
outlook
overcast   0    4
rainy      2    3
sunny      3    2, play         no  yes
temperature
cool          1    3
hot           2    2
mild          2    4, play      no  yes
humidity
high       4    3
normal     1    6, play   no  yes
windy
f       2    6
t       3    3]

In [27]:
    ## Doing Laplacian Correction 
     # Increase size of freuencies by 1
     
for i in range(len(result)):
     lencol=len(result[i].columns)
     lenrow=len(result[i].index)
     for j in range(lenrow):
         for k in range(lencol):
             result[i].iloc[j][k]=result[i].iloc[j][k]+1
result

[play      no  yes
 outlook
 overcast   1    5
 rainy      3    4
 sunny      4    3, play         no  yes
 temperature
 cool          2    4
 hot           3    3
 mild          3    5, play      no  yes
 humidity
 high       5    4
 normal     2    7, play   no  yes
 windy
 f       3    7
 t       4    4]

In [28]:

# Probability Calc             
for i in range(len(result)):
    lencol=len(result[i].columns)
    lenrow=len(result[i].index)
    result[i]['Total']=0
    result[i].loc['Total']=0
    for j in range(lenrow):
     result[i].iloc[j]['Total']=sum(result[i].iloc[j])
    for k in range(lencol+1):
     result[i].loc['Total'][k]=sum(result[i][result[i].columns[k]])
result

[play      no  yes  Total
 outlook
 overcast   1    5      6
 rainy      3    4      7
 sunny      4    3      7
 Total      8   12     20, play         no  yes  Total
 temperature
 cool          2    4      6
 hot           3    3      6
 mild          3    5      8
 Total         8   12     20, play      no  yes  Total
 humidity
 high       5    4      9
 normal     2    7      9
 Total      7   11     18, play   no  yes  Total
 windy
 f       3    7     10
 t       4    4      8
 Total   7   11     18]

In [29]:

# Convert int64 to flaot in all values     
for i in range(len(result)):
  result[i]=result[i].astype(float)     
     
for i in range(len(result)):
     lencol=len(result[i].columns)
     lenrow=len(result[i].index)
     for j in range(lenrow):
         for k in range(lencol):
             if k==lencol-1:
               result[i].iloc[j][k]=(result[i].iloc[j][k])/(result[i].loc['Total']['Total'])  
             else:
               result[i].iloc[j][k]=(result[i].iloc[j][k])/(result[i].iloc[j][lencol-1])
result

[play            no       yes  Total
 outlook
 overcast  0.166667  0.833333   0.30
 rainy     0.428571  0.571429   0.35
 sunny     0.571429  0.428571   0.35
 Total     0.400000  0.600000   1.00, play               no       yes  Total
 temperature
 cool         0.333333  0.666667    0.3
 hot          0.500000  0.500000    0.3
 mild         0.375000  0.625000    0.4
 Total        0.400000  0.600000    1.0, play            no       yes  Total
 humidity
 high      0.555556  0.444444    0.5
 normal    0.222222  0.777778    0.5
 Total     0.388889  0.611111    1.0, play         no       yes     Total
 windy
 f      0.300000  0.700000  0.555556
 t      0.500000  0.500000  0.444444
 Total  0.388889  0.611111  1.000000]

In [30]:

    
## Conditional probabilities

 # Taking random sample
classes=len(list(result[0].columns))-1
features=len(data.columns)-1
Classes=list(result[0].columns)

Feat=[]
#for i in range(feat-1):
 #   var.append('Feat'+str(i))
    
for i in range(features):   
    temp=len(result[i].index)-1
    Feat.append(list(result[i].index[0:temp]))

Rsample=[]    
for i in range(features):    
 Rsample.append(rand.sample(Feat[i],1))

P=[]
# Finding conditional probability per class

for i in range(classes):
    P.append(result[0].loc[Rsample[0]][Classes[i]][0]*result[1].loc[Rsample[1]][Classes[i]][0]*result[2].loc[Rsample[2]][Classes[i]][0]*result[3].loc[Rsample[3]][Classes[i]][0]*result[0].loc['Total'][Classes[i]])
#print(P)    
    s=sum(P)
for i in range(len(P)):
    P[i]=P[i]/s
print('\n')    
print('Random sample formed is:\n')       
print(Rsample)
print('\n')
id=P.index(max(P))
print('Most Probable Class is\n',Classes[id], '\nWith', P[id]*100 ,'%')

Random sample formed is:

[['rainy'], ['mild'], ['normal'], ['f']]


Most Probable Class is
 yes
With 96.45669291338584 %